//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWordsUrkAdminConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string TheGame { get; set; }
        public int Complexity { get; set; }
        public string Description { get; set; }
        public string IncludedFromVer { get; set; }
        public int State { get; set; }
        public string LastModified { get; set; }
        public Nullable<System.DateTime> ExcludedFromVer { get; set; }
    }
}
