//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWordsUrkAdminConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public GameType Type { get; set; }
        public string TheGame { get; set; }
        public GameComplexity Complexity { get; set; }
        public string Description { get; set; }
        public GameState State { get; set; }
        public int IncludedFromVerId { get; set; }
        public Nullable<int> ExcludedFromVerId { get; set; }
        public string LastModified { get; set; }
        public int UserId { get; set; }
    
        public virtual User ModifiedBy { get; set; }
        public virtual Version IncludedFromVer { get; set; }
        public virtual Version ExcludedFromVer { get; set; }
    }
}
