//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWordsUrkAdminConsole.Models
{
    using System;
    
    public enum GameState : int
    {
        New = 0,
        ToVerify = 1,
        Testing = 2,
        Live = 3,
        Rejected = 4
    }
}
