//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWordsUrkAdminConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> WordId { get; set; }
        public string Url { get; set; }
        public int State { get; set; }
        public int IncludedFromVerId { get; set; }
        public Nullable<int> ExcludedFromVerId { get; set; }
        public System.DateTime LastModified { get; set; }
        public int UserId { get; set; }
    
        public virtual Word Word { get; set; }
        public virtual User ModifiedBy { get; set; }
        public virtual Version IncludedFromVer { get; set; }
        public virtual Version ExcludedFromVer { get; set; }
    }
}
