//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWordsUrkAdminConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string InternalNotes { get; set; }
        public VersionState State { get; set; }
        public System.DateTime LastModified { get; set; }
        public int UserId { get; set; }
    
        public virtual User ModifiedBy { get; set; }
    }
}
