//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWordsUrkAdminConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Word()
        {
            this.Clues = new HashSet<Clue>();
        }
    
        public int Id { get; set; }
        public string TheWord { get; set; }
        public string Definition { get; set; }
        public WordArea Area { get; set; }
        public WordComplexity Complexity { get; set; }
        public WordState State { get; set; }
        public System.DateTime LastModified { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clue> Clues { get; set; }
        public virtual User ModifiedBy { get; set; }
    }
}
