//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWordsUrkAdminConsole.Models
{
    using System;
    
    public enum WordArea : int
    {
        Unclassified = 0,
        General = 1,
        Geography = 2,
        City = 3,
        Country = 4,
        Name = 5
    }
}
