//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWordsUrkAdminConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Words
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Words()
        {
            this.Status = 0;
        }
    
        public int Id { get; set; }
        public string Word { get; set; }
        public string Definition { get; set; }
        public string Clue { get; set; }
        public int Status { get; set; }
        public System.DateTime LastModified { get; set; }
        public int Complexity { get; set; }
        public string IncludedFromVerion { get; set; }
    }
}
